### ISSUE TITLE
Good start

### ISSUE THREAD

**Issue by fhoda** [Victor-Villacis/RockPaperScissors#1]
You have a good start on it but it needs some polishing. I suggest incrementing the scores and roundCount automatically instead of asking the user to do so. Also let the user know what the computer picked. And your stop/start button doesn't do anything at the moment. 

Some things to note:
- Put your css in its own "css" folder.
- Start to comment your code. This will help you debug or return to your code in the future as well as help other understand your thought process.

**Comment by Victor-Villacis** [comment]
done, thanks for the feedback lol
